# Generated by Django 5.1.15 on 2026-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("LAB_RESULT", "Lab Result"),
                    ("PRESCRIPTION", "Prescription"),
                    ("DIAGNOSIS", "Diagnosis"),
                    ("IMAGING", "Imaging"),
                    ("CONSULTATION", "Consultation"),
                    ("DISCHARGE_SUMMARY", "Discharge Summary"),
                    ("VISIT_SUMMARY", "Visit Summary"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=30,
            ),
        ),
    ]
