# Generated by Django 5.1.15 on 2026-06-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('TREATMENT', 'Treatment'), ('RESEARCH', 'Research'), ('INSURANCE', 'Insurance'), ('BILLING', 'Billing'), ('EMERGENCY', 'Emergency'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_grants', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Consent',
                'verbose_name_plural': 'Consents',
                'db_table': 'consents',
                'ordering': ['-granted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'staff', 'purpose'), name='unique_active_consent')],
            },
        ),
    ]
