# Generated by Django 5.1.15 on 2026-06-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
        ('patients', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consent',
            name='unique_active_consent',
        ),
        migrations.RemoveField(
            model_name='consent',
            name='is_active',
        ),
        migrations.AddField(
            model_name='consent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GRANTED', 'Granted'), ('DENIED', 'Denied'), ('REVOKED', 'Revoked')], default='PENDING', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'GRANTED')), fields=('patient', 'staff', 'purpose'), name='unique_granted_consent'),
        ),
    ]
