# Generated by Django 5.1.15 on 2026-06-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='EGP', max_length=3)),
                ('payment_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB_TEST', 'Lab Test'), ('MEDICATION', 'Medication'), ('PROCEDURE', 'Procedure'), ('INSURANCE_COPAY', 'Insurance Co-pay'), ('OTHER', 'Other')], max_length=20)),
                ('gateway_type', models.CharField(choices=[('FAWRY', 'Fawry'), ('CARD', 'Card (Visa/Mastercard)'), ('CASH', 'Cash')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('gateway_reference_id', models.CharField(blank=True, default='', help_text='Transaction ID from the payment gateway.', max_length=255)),
                ('receipt_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
