# Generated by Django 5.1.15 on 2026-06-19 05:48

import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='working_hours',
            field=models.JSONField(blank=True, default=staff.models.default_working_hours, help_text="Doctor's weekly schedule"),
        ),
    ]
