# Generated by Django 5.1.15 on 2026-06-03 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('RECORD_VIEW', 'Record Viewed'), ('RECORD_CREATE', 'Record Created'), ('RECORD_UPDATE', 'Record Updated'), ('RECORD_DELETE', 'Record Deleted'), ('DOCUMENT_UPLOAD', 'Document Uploaded'), ('DOCUMENT_DOWNLOAD', 'Document Downloaded'), ('DOCUMENT_DELETE', 'Document Deleted'), ('CONSENT_GRANT', 'Consent Granted'), ('CONSENT_REVOKE', 'Consent Revoked'), ('PAYMENT_INITIATE', 'Payment Initiated'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_REFUND', 'Payment Refunded'), ('STAFF_CREATE', 'Staff Created'), ('STAFF_UPDATE', 'Staff Updated'), ('STAFF_DELETE', 'Staff Deactivated'), ('APPOINTMENT_CREATE', 'Appointment Created'), ('APPOINTMENT_UPDATE', 'Appointment Updated'), ('APPOINTMENT_CANCEL', 'Appointment Cancelled'), ('OTHER', 'Other')], max_length=30)),
                ('entity_type', models.CharField(choices=[('USER', 'User'), ('PATIENT', 'Patient'), ('STAFF', 'Staff'), ('RECORD', 'Medical Record'), ('DOCUMENT', 'Document'), ('CONSENT', 'Consent'), ('PAYMENT', 'Payment'), ('APPOINTMENT', 'Appointment'), ('NOTIFICATION', 'Notification'), ('HOSPITAL', 'Hospital')], max_length=20)),
                ('entity_id', models.CharField(help_text='Primary key of the affected entity.', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context about the action (e.g., changed fields).')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(help_text='User who performed the action. Null if system action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
